### ISSUE TITLE
stringByTrimmingTrailingWhitespaceAndNewlineCharacters Missing

### ISSUE THREAD

**Issue by williamsjj** [soffes/SAMCategories#21]
Just upgraded to SSToolkit 2.0 and code that depended on stringByTrimmingTrailingWhitespaceAndNewlineCharacters no longer works. Did it move to a different module?

-J

**Comment by soffes** [comment]
Those were removed awhile ago from SSToolkit so they never made it to SAMCategories. Sorry.

**Comment by soffes** [comment]
You can do this with plain NSString:

``` objc
[foo stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
```

**Comment by williamsjj** [comment]
Thanks. stringByTrimmingTrailingWhitespaceAndNewlineCharacters was about 25% shorter and much easier to read semantically.
