### ISSUE TITLE
Using with CocoaPods and Swift

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [soffes/SAMCategories#27]
I have CocoaPods 0.36 beta which supports Swift installed. Usually I can install Objective-C dependencies through that as well. I'm having an issue trying to add SAMCategories
 though.

I created the following `Podfile`.

```
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

pod 'SAMCategories'
```

Ran `pod install` and the library gets integrated as a framework. Build it and no issues came up.

Now to use the methods from this library, I need to import it to the file so I added the line `import SAMCategories` to a file and build it again. Then I get the following errors.
**/Users/isurunanayakkara/Developer/Xcode Projects/Swift/ISODateConverting/Pods/SAMCategories/SAMCategories/NSString+SAMAdditions.h:10:9: Include of non-modular header inside framework module 'SAMCategories.NSString_SAMAdditions'**

and this.
**Could not build Objective-C module 'SAMCategories'**

Any idea why this is happening? I have added Objective-C libraries to Swift projects using CocoaPods and used them with no problem. I can't figure out what's wrong here.

**Comment by soffes** [comment]
My understanding is that pods should work as frameworks without modifications. I think this is a CocoaPods bug. Any ideas @orta?

**Comment by Isuru-Nanayakkara** [comment]
hmm I think it might be a CocoaPods bug too. Its not the first time I came across this [issue](https://github.com/magicalpanda/MagicalRecord/issues/943) trying to use an Objective-C library through CocoaPods.
