### ISSUE TITLE
NSDate+SAMAdditions __stack_chk_fail in strptime

### ISSUE THREAD

**Issue by jpicerno** [soffes/SAMCategories#28]
Hi,
I'm using this library and I have same problems, that i could not see what could it be.
The problem is when using 
NSDate+SAMAdditions to parse iso8601 using the function 
    `+(NSDate *)sam_dateFromISO8601String:(NSString *)iso8601;`

I have a __stack_chk_fail when it try to use strptime at line 81.
I used this date to parse "2015-03-26T18:08:22.388461"
Regards
Juan

**Comment by soffes** [comment]
Use [ISO8601](https://github.com/soffes/ISO8601) instead

**Comment by jpicerno** [comment]
Ok, I thought that could parse any similar type!
thanks
